// Code generated by Modus. DO NOT EDIT.

package main

import (
	"nfe-modus/api/internal/auth"
	"github.com/hypermodeinc/modus/sdk/go/pkg/console"
)

func main() {}

//go:export generateOTP
func __modus_GenerateOTP(req *auth.GenerateOTPRequest) *auth.GenerateOTPResponse {
	r0, err := GenerateOTP(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export verifyOTP
func __modus_VerifyOTP(req *auth.VerifyOTPRequest) *auth.VerifyOTPResponse {
	r0, err := VerifyOTP(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

