// Code generated by Modus. DO NOT EDIT.

package main

import (
	"nfe-modus/api/functions/auth"
	"nfe-modus/api/functions/user"
	"github.com/hypermodeinc/modus/sdk/go/pkg/console"
)

//go:export generateOTP
func __modus_GenerateOTP(req *auth.GenerateOTPRequest) *auth.GenerateOTPResponse {
	r0, err := GenerateOTP(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export verifyOTP
func __modus_VerifyOTP(req *auth.VerifyOTPRequest) *auth.VerifyOTPResponse {
	r0, err := VerifyOTP(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export getUserTimestamps
func __modus_GetUserTimestamps(req *user.GetUserTimestampsInput) *user.UserTimestamps {
	r0, err := GetUserTimestamps(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export registerWebAuthn
func __modus_RegisterWebAuthn(req *auth.WebAuthnRegistrationRequest) *auth.WebAuthnRegistrationResponse {
	r0, err := RegisterWebAuthn(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export verifyWebAuthn
func __modus_VerifyWebAuthn(req *auth.WebAuthnVerificationRequest) *auth.WebAuthnVerificationResponse {
	r0, err := VerifyWebAuthn(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export setPassphrase
func __modus_SetPassphrase(req *auth.SetPassphraseRequest) *auth.SetPassphraseResponse {
	r0, err := SetPassphrase(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

//go:export verifyPassphrase
func __modus_VerifyPassphrase(req *auth.VerifyPassphraseRequest) *auth.VerifyPassphraseResponse {
	r0, err := VerifyPassphrase(req)
	if err != nil {
		console.Error(err.Error())
	}
	return r0
}

